#spring:
#  datasource:
#    password: root
#    url: jdbc:postgresql://localhost:5432/gerenciador_funcionarios
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
#
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
